name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      API_BASE_URL: "http://localhost:4000"
      GRAPHQL_PATH: "/graphql"
      LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }}
      LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
      SENDER_OK_ID: "alice"
      RECEIVER_OK_ID: "bob"
      SENDER_NO_FUNDS_ID: "user_sem_saldo"
      AMOUNT_SUCCESS: "50"
      AMOUNT_NO_FUNDS: "999999"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run controller tests
        run: npm run test-controller

      - name: Start GraphQL API
        run: npm run start-graphql &

      - name: Wait for API to be ready
        run: npx --yes wait-on http://localhost:4000/graphql

      - name: Run external API tests
        run: npm run test-external

      - name: Upload mochawesome report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: mochawesome-report/
